Flyteam outfit:
-TriggerEvent('skinchanger:loadSkin', {
                    sex          = 0,
                    face         = 0,
                    skin         = 3,
                    hair_1       = 0,
                    hair_2       = 0,
                    hair_color_1 = 0,
                    hair_color_2 = 0,
                    decals_1     = 0,
                    decals_2     = 0,
                    tshirt_1     = 15,
                    tshirt_2     = 0,
                    torso_1      = 105,
                    torso_2      = 0,
                    arms         = 0,
                    pants_1      = 42,
                    pants_2      = 2,
                    shoes_1      = 6,
                    shoes_2      = 0,
                    helmet_1     = 2,
                    helmet_2     = 3,
                    mask_1       = 0,
                    mask_2       = 0,
                    bproof_1     = 0,
                    bproof_2     = 0,
                    bags_1         = 0,
                    bags_2         = 0,
                    beard_1      = 0,
                    beard_2      = 0,
                    beard_3      = 0,
                    beard_4      = 0,
                    chain_1      = 0,
                    chain_2      = 0,
                    glasses_1    = 0,
                    glasses_2    = 0,
                        }) 


 Hitler outfit:
-TriggerEvent('skinchanger:loadSkin', {
                    sex          = 0,
                    face         = 13,
                    skin         = 1,
                    hair_1       = 18,
                    hair_2       = 0,
                    hair_color_1 = 0,
                    hair_color_2 = 0,
                    decals_1     = 0,
                    decals_2     = 0,
                    tshirt_1     = 10,
                    tshirt_2     = 0,
                    torso_1      = 72,
                    torso_2      = 1,
                    arms         = 33,
                    pants_1      = 24,
                    pants_2      = 1,
                    shoes_1      = 38,
                    shoes_2      = 0,
                    mask_1       = 0,
                    mask_2       = 0,
                    helmet_1       = 113,
                    helmet_2       = 0,
                    bproof_1     = 0,
                    bproof_2     = 0,
                    bags_1         = 0,
                    bags_2         = 0,
                    beard_1      = 9,
                    beard_2      = 10,
                    beard_3      = 0,
                    beard_4      = 0,
                    chain_1      = 38,
                    chain_2      = 0,
                    glasses_1    = 0,
                    glasses_2    = 0,
                        })


 Civi outfit:
-TriggerEvent('skinchanger:loadSkin', {
                    sex          = 0,
                    face         = 0,
                    skin         = 0,
                    hair_1       = 1,
                    hair_2       = 0,
                    hair_color_1 = 0,
                    hair_color_2 = 0,
                    decals_1     = 0,
                    decals_2     = 0,
                    tshirt_1     = 8,
                    tshirt_2     = 13,
                    torso_1      = 7,
                    torso_2      = 2,
                    arms         = 4,
                    pants_1      = 24,
                    pants_2      = 0,
                    shoes_1      = 8,
                    shoes_2      = 0,
                    mask_1       = 0,
                    mask_2       = 0,
                    bproof_1     = 0,
                    bproof_2     = 0,
                    bags_1         = 0,
                    bags_2         = 0,
                    beard_1      = 0,
                    beard_2      = 0,
                    beard_3      = 0,
                    beard_4      = 0,
                    chain_1      = 0,
                    chain_2      = 0,
                    glasses_1    = 0,
                    glasses_2    = 0,
                        })


 Caillou outfit:
-TriggerEvent('skinchanger:loadSkin', {
                    sex          = 0,
                    face         = 0,
                    skin         = 0,
                    hair_1       = 0,
                    hair_2       = 0,
                    hair_color_1 = 0,
                    hair_color_2 = 0,
                    decals_1     = 0,
                    decals_2     = 0,
                    tshirt_1     = 0,
                    tshirt_2     = 0,
                    torso_1      = 0,
                    torso_2      = 0,
                    arms         = 0,
                    pants_1      = 0,
                    pants_2      = 0,
                    shoes_1      = 0,
                    shoes_2      = 0,
                    mask_1       = 0,
                    mask_2       = 0,
                    bproof_1     = 0,
                    bproof_2     = 0,
                    bags_1         = 0,
                    bags_2         = 0,
                    beard_1      = 0,
                    beard_2      = 0,
                    beard_3      = 0,
                    beard_4      = 0,
                    chain_1      = 0,
                    chain_2      = 0,
                    glasses_1    = 0,
                    glasses_2    = 0,
                        })
