-TriggerServerEvent('esx_policejob:message', -1, "RDM & VDM is now allowed...")
-TriggerServerEvent('enp-admin:announce',-1, "You Got Fucked")
-TriggerServerEvent('sp_police:message',  -1, "oh")
-TriggerEvent('messagerundruf:show',"Diamond team", "RDM & VDM is now allowed...")
